CREATE SEQUENCE  IF NOT EXISTS primary_sequence START WITH 10000 INCREMENT BY 1;

CREATE TABLE "TB_USERS" (
    "ID" BIGINT NOT NULL,
    "NAME" VARCHAR(255) NOT NULL,
    "OPENID" VARCHAR(255),
    "LOGIN_TYPE" VARCHAR(255),
    "HASH" VARCHAR(255),
    "ROLE_ID" BIGINT,
    "DATE_CREATED" TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    "LAST_UPDATED" TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT "PK_USERS" PRIMARY KEY ("ID")
);

CREATE TABLE "TB_ROLES" (
    "ID" BIGINT NOT NULL,
    "NAME" VARCHAR(255) NOT NULL,
    "DATE_CREATED" TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    "LAST_UPDATED" TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT "PK_ROLES" PRIMARY KEY ("ID")
);

ALTER TABLE "TB_USERS" ADD CONSTRAINT "FK_USERS_ROLE_ID" FOREIGN KEY ("ROLE_ID") REFERENCES "TB_ROLES" ("ID") ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "TB_USERS" ADD CONSTRAINT "UNIQUE_USERS_NAME" UNIQUE ("NAME");

ALTER TABLE "TB_ROLES" ADD CONSTRAINT "UNIQUE_ROLES_NAME" UNIQUE ("NAME");
